const express = require('express');
const body_parser = require('body-parser');
const bcrypt = require('bcrypt');
const morgan = require('morgan');
const userRouter = require('./routers/userRouter');
const scrapeRouter = require('./routers/scrapeRouter');
const otpRouter = require('./routers/otpRouter');
const weatherRouter = require('./routers/weatherRouter');
const complaintRouter = require('./routers/complaintRouter');
const memberNotificationRouter = require('./routers/memberNotificationRouter');
const officerNotificationRouter = require('./routers/officerNotificationRouter');
const fileUpload = require('express-fileupload');
const app = express();
app.use(body_parser.json());

app.use(fileUpload());
app.use(morgan('tiny'));
app.use('/',userRouter);
app.use('/',scrapeRouter);
app.use('/',otpRouter);
app.use('/',weatherRouter);
app.use('/',complaintRouter);
app.use('/',memberNotificationRouter);
app.use('/',officerNotificationRouter);
module.exports=app;